/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ai/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Backtest */
        post: operations["explain_backtest_ai_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ai/strategy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Strategy */
        post: operations["generate_strategy_ai_strategy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_auth_change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Issue a CSRF token (sets cookie + returns token) */
        get: operations["issue_csrf_auth_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Account */
        post: operations["delete_account_auth_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Password Reset
         * @description Start a reset. Always a generic 200 (no account enumeration); emails a link when real.
         */
        post: operations["password_reset_auth_password_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset-confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Password Reset Confirm */
        post: operations["password_reset_confirm_auth_password_reset_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Backtests */
        get: operations["list_backtests_backtests_get"];
        put?: never;
        /** Create Backtest */
        post: operations["create_backtest_backtests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtests/{backtest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Backtest */
        get: operations["get_backtest_backtests__backtest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brokers/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connections */
        get: operations["list_connections_brokers_connections_get"];
        put?: never;
        /** Add Connection */
        post: operations["add_connection_brokers_connections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Live Order */
        post: operations["submit_live_order_live_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/live/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live Preflight */
        get: operations["live_preflight_live_preflight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Instruments */
        get: operations["list_instruments_market_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/instruments/{instrument_id}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Instrument Bars */
        get: operations["get_instrument_bars_market_instruments__instrument_id__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/instruments/{instrument_id}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Quote */
        get: operations["latest_quote_market_instruments__instrument_id__latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/market/ws-ticket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Ws Ticket */
        post: operations["create_ws_ticket_market_ws_ticket_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deploy */
        post: operations["deploy_paper_deploy_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_paper_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_paper_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/sessions/{session_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Now */
        post: operations["run_now_paper_sessions__session_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/paper/sessions/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_paper_sessions__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (DB + Redis) */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_strategies_get"];
        put?: never;
        /** Create Strategy */
        post: operations["create_strategy_strategies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{strategy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy */
        get: operations["get_strategy_strategies__strategy_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{strategy_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Versions */
        get: operations["list_versions_strategies__strategy_id__versions_get"];
        put?: never;
        /** Add Version */
        post: operations["add_version_strategies__strategy_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/strategies/{strategy_id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Version */
        get: operations["get_version_strategies__strategy_id__versions__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestOut */
        BacktestOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * End Ts
             * Format: date-time
             */
            end_ts: string;
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /** Status */
            status: string;
            /**
             * Strategy Id
             * Format: uuid
             */
            strategy_id: string;
            /** Strategy Version */
            strategy_version: number;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** BacktestSummaryOut */
        BacktestSummaryOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * End Ts
             * Format: date-time
             */
            end_ts: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /** Status */
            status: string;
            /**
             * Strategy Id
             * Format: uuid
             */
            strategy_id: string;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** BarOut */
        BarOut: {
            /** Close */
            close: string;
            /** High */
            high: string;
            /** Low */
            low: string;
            /** Open */
            open: string;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Volume */
            volume: string;
        };
        /** BrokerConnectionCreate */
        BrokerConnectionCreate: {
            /** Api Key */
            api_key: string;
            /** Api Secret */
            api_secret: string;
            /** Broker */
            broker: string;
            /**
             * Env
             * @default paper
             * @enum {string}
             */
            env: "paper" | "live";
            /** Label */
            label?: string | null;
        };
        /** BrokerConnectionOut */
        BrokerConnectionOut: {
            /** Broker */
            broker: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Env */
            env: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Label */
            label: string | null;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /** Current Password */
            current_password: string;
            /** New Password */
            new_password: string;
        };
        /** Comparison */
        Comparison: {
            left: components["schemas"]["Operand"];
            /**
             * Op
             * @enum {string}
             */
            op: ">" | "<" | ">=" | "<=" | "cross_above" | "cross_below";
            right: components["schemas"]["Operand"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "compare";
        };
        /** CreateBacktestRequest */
        CreateBacktestRequest: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * Strategy Id
             * Format: uuid
             */
            strategy_id: string;
        };
        /** DeleteAccountRequest */
        DeleteAccountRequest: {
            /** Password */
            password: string;
        };
        /** DeployRequest */
        DeployRequest: {
            /**
             * Strategy Id
             * Format: uuid
             */
            strategy_id: string;
        };
        /** ExitRule */
        "ExitRule-Input": {
            /** Exit Conditions */
            exit_conditions?: (components["schemas"]["Comparison"] | components["schemas"]["Group-Input"]) | null;
            /** Stop Loss Pct */
            stop_loss_pct?: number | null;
            /** Take Profit Pct */
            take_profit_pct?: number | null;
            /** Time Exit Bars */
            time_exit_bars?: number | null;
            /** Trailing Stop Pct */
            trailing_stop_pct?: number | null;
        };
        /** ExitRule */
        "ExitRule-Output": {
            /** Exit Conditions */
            exit_conditions?: (components["schemas"]["Comparison"] | components["schemas"]["Group-Output"]) | null;
            /** Stop Loss Pct */
            stop_loss_pct?: number | null;
            /** Take Profit Pct */
            take_profit_pct?: number | null;
            /** Time Exit Bars */
            time_exit_bars?: number | null;
            /** Trailing Stop Pct */
            trailing_stop_pct?: number | null;
        };
        /** ExplainRequest */
        ExplainRequest: {
            /** Context */
            context: {
                [key: string]: unknown;
            };
        };
        /** ExplainResponse */
        ExplainResponse: {
            /** Provider */
            provider: string;
            /** Text */
            text: string;
        };
        /** GenerateStrategyRequest */
        GenerateStrategyRequest: {
            /** Prompt */
            prompt: string;
        };
        /** GenerateStrategyResponse */
        GenerateStrategyResponse: {
            /** Provider */
            provider: string;
            spec: components["schemas"]["StrategySpec-Output"];
        };
        /** Group */
        "Group-Input": {
            /** Conditions */
            conditions: (components["schemas"]["Comparison"] | components["schemas"]["Group-Input"])[];
            /**
             * Logic
             * @enum {string}
             */
            logic: "all" | "any";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "group";
        };
        /** Group */
        "Group-Output": {
            /** Conditions */
            conditions: (components["schemas"]["Comparison"] | components["schemas"]["Group-Output"])[];
            /**
             * Logic
             * @enum {string}
             */
            logic: "all" | "any";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "group";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndicatorSpec */
        IndicatorSpec: {
            /** Id */
            id: string;
            /** Params */
            params?: {
                [key: string]: number;
            };
            /**
             * Type
             * @enum {string}
             */
            type: "EMA" | "SMA" | "RSI" | "ATR" | "BBANDS" | "MACD" | "VWAP" | "VOL_SMA";
        };
        /** InstrumentOut */
        InstrumentOut: {
            /** Asset Class */
            asset_class: string;
            /** Calendar */
            calendar: string;
            /** Exchange */
            exchange: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string | null;
            /** Quote Currency */
            quote_currency: string;
            /** Symbol */
            symbol: string;
        };
        /** LiveOrderRequest */
        LiveOrderRequest: {
            /**
             * Broker Connection Id
             * Format: uuid
             */
            broker_connection_id: string;
            /** Confirmation Token */
            confirmation_token?: string | null;
            /** Qty */
            qty: number;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Symbol */
            symbol: string;
        };
        /** LivePreflightOut */
        LivePreflightOut: {
            /** Allowed */
            allowed: boolean;
            /** Blocked Reasons */
            blocked_reasons: string[];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** Operand */
        Operand: {
            /** Field */
            field?: ("open" | "high" | "low" | "close" | "volume") | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "price" | "indicator" | "const";
            /**
             * Multiplier
             * @default 1
             */
            multiplier: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
            /** Output */
            output?: string | null;
            /** Ref */
            ref?: string | null;
            /** Value */
            value?: number | null;
        };
        /** PaperSessionOut */
        PaperSessionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Initial Cash */
            initial_cash: string;
            /** Last Run At */
            last_run_at: string | null;
            /**
             * Session Start
             * Format: date-time
             */
            session_start: string;
            /** Snapshot */
            snapshot: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
            /**
             * Strategy Id
             * Format: uuid
             */
            strategy_id: string;
            /** Strategy Version */
            strategy_version: number;
            /** Symbol */
            symbol: string;
            /** Timeframe */
            timeframe: string;
        };
        /** PasswordResetConfirm */
        PasswordResetConfirm: {
            /** New Password */
            new_password: string;
            /** Token */
            token: string;
        };
        /** PasswordResetRequest */
        PasswordResetRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** PositionSizing */
        PositionSizing: {
            /** Atr Ref */
            atr_ref?: string | null;
            /**
             * Method
             * @enum {string}
             */
            method: "fixed_units" | "percent_equity" | "risk_per_trade" | "atr";
            /** Value */
            value: number;
        };
        /** QuoteOut */
        QuoteOut: {
            /**
             * Instrument Id
             * Format: uuid
             */
            instrument_id: string;
            /** Price */
            price: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Display Name */
            display_name?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RiskLimits */
        RiskLimits: {
            /** Max Consecutive Losses */
            max_consecutive_losses?: number | null;
            /** Max Daily Loss Pct */
            max_daily_loss_pct?: number | null;
            /**
             * Max Open Positions
             * @default 1
             */
            max_open_positions: number;
            /**
             * Max Position Pct
             * @default 1
             */
            max_position_pct: number;
        };
        /** StrategyDetailOut */
        StrategyDetailOut: {
            latest: components["schemas"]["StrategyVersionOut"] | null;
            strategy: components["schemas"]["StrategyOut"];
        };
        /** StrategyOut */
        StrategyOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Latest Version */
            latest_version: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StrategySpec */
        "StrategySpec-Input": {
            /** Entry Long */
            entry_long: components["schemas"]["Comparison"] | components["schemas"]["Group-Input"];
            /** Entry Short */
            entry_short?: (components["schemas"]["Comparison"] | components["schemas"]["Group-Input"]) | null;
            exit: components["schemas"]["ExitRule-Input"];
            /** Indicators */
            indicators?: components["schemas"]["IndicatorSpec"][];
            /** Name */
            name: string;
            risk?: components["schemas"]["RiskLimits"];
            sizing: components["schemas"]["PositionSizing"];
            /**
             * Spec Version
             * @default 1.0
             * @constant
             */
            spec_version: "1.0";
            time_of_day?: components["schemas"]["TimeOfDayFilter"] | null;
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
            /** Universe */
            universe: string[];
        };
        /** StrategySpec */
        "StrategySpec-Output": {
            /** Entry Long */
            entry_long: components["schemas"]["Comparison"] | components["schemas"]["Group-Output"];
            /** Entry Short */
            entry_short?: (components["schemas"]["Comparison"] | components["schemas"]["Group-Output"]) | null;
            exit: components["schemas"]["ExitRule-Output"];
            /** Indicators */
            indicators?: components["schemas"]["IndicatorSpec"][];
            /** Name */
            name: string;
            risk?: components["schemas"]["RiskLimits"];
            sizing: components["schemas"]["PositionSizing"];
            /**
             * Spec Version
             * @default 1.0
             * @constant
             */
            spec_version: "1.0";
            time_of_day?: components["schemas"]["TimeOfDayFilter"] | null;
            /**
             * Timeframe
             * @enum {string}
             */
            timeframe: "1m" | "5m" | "15m" | "1h" | "4h" | "1d";
            /** Universe */
            universe: string[];
        };
        /** StrategyVersionOut */
        StrategyVersionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Engine Version */
            engine_version: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            spec: components["schemas"]["StrategySpec-Output"];
            /** Spec Hash */
            spec_hash: string;
            /**
             * Strategy Id
             * Format: uuid
             */
            strategy_id: string;
            /** Version */
            version: number;
        };
        /** TimeOfDayFilter */
        TimeOfDayFilter: {
            /** End */
            end: string;
            /** Start */
            start: string;
            /**
             * Timezone
             * @default exchange
             * @enum {string}
             */
            timezone: "exchange" | "utc";
        };
        /** UserOut */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Display Name */
            display_name: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WsTicketOut */
        WsTicketOut: {
            /** Expires In */
            expires_in: number;
            /** Ticket */
            ticket: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    explain_backtest_ai_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_strategy_ai_strategy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateStrategyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateStrategyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_auth_change_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_csrf_auth_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    delete_account_auth_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    password_reset_auth_password_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    password_reset_confirm_auth_password_reset_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_backtests_backtests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestSummaryOut"][];
                };
            };
        };
    };
    create_backtest_backtests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_backtest_backtests__backtest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                backtest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_connections_brokers_connections_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerConnectionOut"][];
                };
            };
        };
    };
    add_connection_brokers_connections_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BrokerConnectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerConnectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    submit_live_order_live_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveOrderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_preflight_live_preflight_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivePreflightOut"];
                };
            };
        };
    };
    list_instruments_market_instruments_get: {
        parameters: {
            query?: {
                asset_class?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_instrument_bars_market_instruments__instrument_id__bars_get: {
        parameters: {
            query?: {
                timeframe?: string;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BarOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_quote_market_instruments__instrument_id__latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ws_ticket_market_ws_ticket_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WsTicketOut"];
                };
            };
        };
    };
    deploy_paper_deploy_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_paper_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSessionOut"][];
                };
            };
        };
    };
    get_session_paper_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_now_paper_sessions__session_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_paper_sessions__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_strategies_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"][];
                };
            };
        };
    };
    create_strategy_strategies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategySpec-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_strategy_strategies__strategy_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_versions_strategies__strategy_id__versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_version_strategies__strategy_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategySpec-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_version_strategies__strategy_id__versions__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
