"""paper_sessions

Revision ID: 91d0566854c9
Revises: b13d9815e40d
Create Date: 2026-06-03 19:01:21.641014
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "91d0566854c9"
down_revision: str | None = "b13d9815e40d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_sessions",
        sa.Column("strategy_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_version", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("initial_cash", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("session_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_paper_sessions_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"],
            ["strategies.id"],
            name=op.f("fk_paper_sessions_strategy_id_strategies"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_sessions")),
    )
    op.create_index(
        op.f("ix_paper_sessions_owner_id"), "paper_sessions", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_paper_sessions_strategy_id"), "paper_sessions", ["strategy_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_paper_sessions_strategy_id"), table_name="paper_sessions")
    op.drop_index(op.f("ix_paper_sessions_owner_id"), table_name="paper_sessions")
    op.drop_table("paper_sessions")
    # ### end Alembic commands ###
