"""market data (instruments, sources, ohlcv hypertable)

Revision ID: ee76d2a81338
Revises: 0addaba53686
Create Date: 2026-06-03 15:52:32.044024
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ee76d2a81338"
down_revision: str | None = "0addaba53686"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruments",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("asset_class", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=True),
        sa.Column("exchange", sa.String(length=32), nullable=True),
        sa.Column("quote_currency", sa.String(length=8), nullable=False),
        sa.Column("calendar", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("symbol", "asset_class", name="uq_instruments_symbol_class"),
    )
    op.create_index(op.f("ix_instruments_symbol"), "instruments", ["symbol"], unique=False)
    op.create_table(
        "instrument_sources",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_symbol", sa.String(length=64), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_instrument_sources_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instrument_sources")),
        sa.UniqueConstraint(
            "instrument_id", "source", name="uq_instrument_sources_instrument_source"
        ),
    )
    op.create_index(
        op.f("ix_instrument_sources_instrument_id"),
        "instrument_sources",
        ["instrument_id"],
        unique=False,
    )
    op.create_table(
        "ohlcv",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("volume", sa.Numeric(precision=28, scale=8), nullable=False),
        sa.Column("is_final", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_ohlcv_instrument_id_instruments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("instrument_id", "ts", name=op.f("pk_ohlcv")),
    )
    # ### end Alembic commands ###
    # Convert ohlcv into a TimescaleDB hypertable partitioned on `ts` — but ONLY if
    # TimescaleDB is installed. On a plain Postgres (Neon/Supabase/RDS free tiers)
    # ohlcv stays a normal table; reads use portable SQL, so behavior is identical
    # (just without the time-series partitioning optimization).
    op.execute(
        """
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
            PERFORM create_hypertable('ohlcv', 'ts',
              chunk_time_interval => INTERVAL '7 days', if_not_exists => TRUE);
          END IF;
        END $$;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ohlcv")
    op.drop_index(op.f("ix_instrument_sources_instrument_id"), table_name="instrument_sources")
    op.drop_table("instrument_sources")
    op.drop_index(op.f("ix_instruments_symbol"), table_name="instruments")
    op.drop_table("instruments")
    # ### end Alembic commands ###
